---
- yum: name={{ item }} state=installed
  with_items:
  - openssh-server

- service: name=sshd enabled=yes state=started

- lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin without-password" state=present 
  notify: restart sshd

- include: open_fw.yml ssh_port="ssh"
