---
- package: name={{ item }} state=installed
  with_items:
  - openssh-server
  when: ansible_system == 'Linux'

- service: name=sshd enabled=yes state=started

- lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin without-password" state=present 
  notify: verify config and restart sshd

- include: open_fw.yml ssh_port="22"

- include: open_fw.yml ssh_port={{ ansible_port }}
  when: ansible_port is defined
