---
- name: Install openssh
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - openssh-server
  when: ansible_system == 'Linux'

- name: Start sshd service
  service:
    name: sshd
    enabled: yes
    state: started

- name: Make sure that root can only use keys
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin without-password"
    state: present
  notify: verify config and restart sshd

- include_tasks: onion_service.yml
  when: use_onion_service

- include_tasks: open_fw.yml ssh_port="22"

- include_tasks: open_fw.yml ssh_port={{ ansible_port }}
  when: ansible_port is defined and ansible_port != "22"
