---

- name: Add the ssh HiddenServiceDir config to torrc
  blockinfile:
    dest: "{{ torrc }}"
    block: |
      HiddenServiceDir {{ tordir }}/onion_service_ssh
      HiddenServicePort 22 127.0.0.1:22
  notify: restart tor
